/**
 * Mock Data Store for SchoolERP
 * Follows the PRD & Stitch design specs with realistic Indian & international student records.
 */

export const initialSchoolSettings = {
  schoolName: 'St. Jude International Academy',
  affiliationNo: 'CBSE-REG-882194',
  principalName: 'Dr. Sarah Jenkins',
  email: 'admin@stjudeacademy.edu',
  phone: '+91 98234 56780',
  timezone: 'Asia/Kolkata (IST) • UTC+05:30',
  address: '742 Evergreen Way, Academic District, Pune, Maharashtra 411001',
  currency: '₹',
  academicYear: '2024–25',
  currentTerm: 'Term II • Week 12',
  termProgress: 68,
  totalCapacity: 520,
  autoSmsAbsent: true,
  strictRollCallLock: true,
  attendanceThreshold: 75,
};

export const initialClasses = [
  { id: 'cls-1', className: 'Kindergarten', section: 'A', room: 'Room 101', academicYear: '2024–25', classTeacherName: 'Mrs. Eleanor Vance', capacity: 28, enrolledCount: 25, status: 'Active' },
  { id: 'cls-2', className: 'Grade 1', section: 'A', room: 'Room 104', academicYear: '2024–25', classTeacherName: 'Mr. David Sterling', capacity: 30, enrolledCount: 29, status: 'Active' },
  { id: 'cls-3', className: 'Grade 2', section: 'B', room: 'Room 108', academicYear: '2024–25', classTeacherName: 'Ms. Clarissa Brooks', capacity: 30, enrolledCount: 28, status: 'Active' },
  { id: 'cls-4', className: 'Grade 3', section: 'A', room: 'Room 204', academicYear: '2024–25', classTeacherName: 'Mrs. Emily Vance', capacity: 30, enrolledCount: 28, status: 'Active' },
  { id: 'cls-5', className: 'Grade 3', section: 'B', room: 'Room 205', academicYear: '2024–25', classTeacherName: 'Mr. Jonathan Bell', capacity: 30, enrolledCount: 29, status: 'Active' },
  { id: 'cls-6', className: 'Grade 4', section: 'B', room: 'Room 210', academicYear: '2024–25', classTeacherName: 'Mrs. Margaret Hughes', capacity: 30, enrolledCount: 27, status: 'Active' },
  { id: 'cls-7', className: 'Grade 5', section: 'A', room: 'Room 302', academicYear: '2024–25', classTeacherName: 'Dr. Alan Ross', capacity: 32, enrolledCount: 30, status: 'Active' },
  { id: 'cls-8', className: 'Grade 5', section: 'B', room: 'Room 304', academicYear: '2024–25', classTeacherName: 'Mrs. Anita Rao', capacity: 30, enrolledCount: 26, status: 'Active' },
  { id: 'cls-9', className: 'Grade 6', section: 'C', room: 'Room 308', academicYear: '2024–25', classTeacherName: 'Mr. Rajesh Iyer', capacity: 32, enrolledCount: 31, status: 'Active' },
  { id: 'cls-10', className: 'Junior KG', section: 'A', room: 'Playroom 2', academicYear: '2024–25', classTeacherName: 'Ms. Pooja Sharma', capacity: 25, enrolledCount: 22, status: 'Active' },
  { id: 'cls-11', className: 'Senior KG', section: 'A', room: 'Playroom 3', academicYear: '2024–25', classTeacherName: 'Mrs. Kavita Nair', capacity: 25, enrolledCount: 24, status: 'Active' },
  { id: 'cls-12', className: 'Grade 8', section: 'A', room: 'Lab 2', academicYear: '2023–24', classTeacherName: 'Mr. Vikram Sen', capacity: 30, enrolledCount: 0, status: 'Inactive' },
];

export const initialParents = [
  { id: 'par-1', parentName: 'David Chen', phone: '+91 98221 00192', email: 'david.chen@email.com', address: '742 Evergreen Terrace, North Wing', occupation: 'Software Architect', alternateContact: 'Elena Chen (Mother)' },
  { id: 'par-2', parentName: 'Carlos Martinez', phone: '+91 98221 00144', email: 'carlos.m@martinezco.org', address: 'B-14 Silver Oak Residency, Baner', occupation: 'Civil Engineer', alternateContact: 'Maria Martinez (Mother)' },
  { id: 'par-3', parentName: 'Marcus Vance', phone: '+91 98221 00187', email: 'm.vance@inbox.net', address: 'Plot 44, Hill View Enclave, Aundh', occupation: 'Operations Director', alternateContact: 'Claire Vance (Mother)' },
  { id: 'par-4', parentName: 'Raj Patel', phone: '+91 98221 00163', email: 'raj.patel@techgrp.com', address: 'Flat 502, Sky High Towers, Kothrud', occupation: 'Financial Consultant', alternateContact: 'Sunita Patel (Mother)' },
  { id: 'par-5', parentName: 'Jonathan Brown', phone: '+91 98221 00112', email: 'jbrown@apexcorp.com', address: '88 River Road, Kalyani Nagar', occupation: 'Senior Architect', alternateContact: 'Sarah Brown (Mother)' },
  { id: 'par-6', parentName: 'Andrew Wilson', phone: '+91 98221 00177', email: 'a.wilson@designhub.io', address: '12 Palm Meadows, Viman Nagar', occupation: 'Product Designer', alternateContact: 'Rachel Wilson (Mother)' },
  { id: 'par-7', parentName: 'Samuel Knight', phone: '+91 98221 00131', email: 'samuel.knight@lawfirm.com', address: '304 High Street, Camp', occupation: 'Advocate', alternateContact: 'Diana Knight (Mother)' },
  { id: 'par-8', parentName: 'Peter Taylor', phone: '+91 98221 00199', email: 'p.taylor@medcenter.org', address: '19 Park View Avenue, Model Colony', occupation: 'Physician', alternateContact: 'Jessica Taylor (Mother)' },
  { id: 'par-9', parentName: 'Robert Sterling', phone: '+91 98221 00215', email: 'r.sterling@fintech.co', address: '77 Windsor Estate, Senapati Bapat Rd', occupation: 'Banker', alternateContact: 'Linda Sterling (Mother)' },
  { id: 'par-10', parentName: 'Elena Ramirez', phone: '+91 98221 00244', email: 'elena.ramirez@artstudio.com', address: '45 Magnolia Court, Bavdhan', occupation: 'Creative Director', alternateContact: 'Mateo Ramirez (Father)' },
  { id: 'par-11', parentName: 'Vikram Sharma', phone: '+91 98221 00299', email: 'vikram.sharma@corp.in', address: 'A-201 Green Acres, Wakad', occupation: 'IT Manager', alternateContact: 'Priyanka Sharma (Mother)' },
  { id: 'par-12', parentName: 'Sanjay Patil', phone: '+91 98221 00311', email: 'sanjay.patil@agri.com', address: 'Survey 18, Balewadi', occupation: 'Business Owner', alternateContact: 'Smita Patil (Mother)' },
];

export const initialFeeStructures = [
  { id: 'fee-1', classId: 'cls-10', className: 'Junior KG', academicYear: '2024–25', baseTuition: 26000, labTechFee: 4000, totalAnnualFee: 30000, billingCycle: 'Biannual', status: 'Active' },
  { id: 'fee-2', classId: 'cls-11', className: 'Senior KG', academicYear: '2024–25', baseTuition: 28000, labTechFee: 4000, totalAnnualFee: 32000, billingCycle: 'Biannual', status: 'Active' },
  { id: 'fee-3', classId: 'cls-1', className: 'Kindergarten', academicYear: '2024–25', baseTuition: 30000, labTechFee: 5000, totalAnnualFee: 35000, billingCycle: 'Biannual', status: 'Active' },
  { id: 'fee-4', classId: 'cls-2', className: 'Grade 1', academicYear: '2024–25', baseTuition: 36000, labTechFee: 6000, totalAnnualFee: 42000, billingCycle: 'Quarterly', status: 'Active' },
  { id: 'fee-5', classId: 'cls-3', className: 'Grade 2', academicYear: '2024–25', baseTuition: 36000, labTechFee: 6000, totalAnnualFee: 42000, billingCycle: 'Quarterly', status: 'Active' },
  { id: 'fee-6', classId: 'cls-4', className: 'Grade 3', academicYear: '2024–25', baseTuition: 40000, labTechFee: 8000, totalAnnualFee: 48000, billingCycle: 'Quarterly', status: 'Active' },
  { id: 'fee-7', classId: 'cls-6', className: 'Grade 4', academicYear: '2024–25', baseTuition: 42000, labTechFee: 8000, totalAnnualFee: 50000, billingCycle: 'Quarterly', status: 'Active' },
  { id: 'fee-8', classId: 'cls-7', className: 'Grade 5', academicYear: '2024–25', baseTuition: 45000, labTechFee: 10000, totalAnnualFee: 55000, billingCycle: 'Quarterly', status: 'Active' },
  { id: 'fee-9', classId: 'cls-9', className: 'Grade 6', academicYear: '2024–25', baseTuition: 48000, labTechFee: 12000, totalAnnualFee: 60000, billingCycle: 'Quarterly', status: 'Active' },
];

export const initialStudents = [
  {
    id: 'stu-1',
    studentId: 'GR-1042',
    firstName: 'Liam',
    lastName: 'Chen',
    fullName: 'Liam Chen',
    dob: '2016-04-14',
    gender: 'Male',
    age: 8,
    bloodGroup: 'O+',
    classId: 'cls-4',
    className: 'Grade 3 - Section A',
    classSimple: 'Grade 3',
    section: 'A',
    parentId: 'par-1',
    parentName: 'David Chen',
    phone: '+91 98221 00192',
    email: 'david.chen@email.com',
    motherName: 'Elena Chen',
    address: '742 Evergreen Terrace, North Wing, District 4',
    admissionDate: '2022-09-01',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAvcJdoRjK6f_9wA2pSRF0Tl5OY6JclgG2Uesah6AyscwhADfbeHI-plR8eTuXhBju3k-YWzNHyw7fC2USJATOIzKIZzb8f6dw4qxcfx8lG7alCXt3xZxLgpMAtZBcLwd2ReX-s-96NZPbIJVzptqhRUNBvhqN3pnot3RQKP4kadRb6-1KeqBLadahHIZ_YoHDm1CbAyj0Lv6YBctPV4SaqUvAgLwWzIs-UA4cEsidj_vLPucowEmP9',
    attendanceRate: 96.2,
    totalFee: 48000,
    paidFee: 36000,
    pendingFee: 12000,
    feeStatus: 'Partial',
    overdueDays: 0,
    emergencyPhone: '+91 98221 00192',
  },
  {
    id: 'stu-2',
    studentId: 'GR-1043',
    firstName: 'Sophia',
    lastName: 'Martinez',
    fullName: 'Sophia Martinez',
    dob: '2015-11-21',
    gender: 'Female',
    age: 9,
    bloodGroup: 'A+',
    classId: 'cls-5',
    className: 'Grade 3 - Section B',
    classSimple: 'Grade 3',
    section: 'B',
    parentId: 'par-2',
    parentName: 'Carlos Martinez',
    phone: '+91 98221 00144',
    email: 'carlos.m@martinezco.org',
    motherName: 'Maria Martinez',
    address: 'B-14 Silver Oak Residency, Baner, Pune',
    admissionDate: '2022-09-01',
    status: 'Active',
    avatar: '',
    attendanceRate: 98.5,
    totalFee: 48000,
    paidFee: 48000,
    pendingFee: 0,
    feeStatus: 'Paid in Full',
    overdueDays: 0,
    emergencyPhone: '+91 98221 00144',
  },
  {
    id: 'stu-3',
    studentId: 'GR-1044',
    firstName: 'Lucas',
    lastName: 'Vance',
    fullName: 'Lucas Vance',
    dob: '2016-08-09',
    gender: 'Male',
    age: 8,
    bloodGroup: 'B+',
    classId: 'cls-4',
    className: 'Grade 3 - Section A',
    classSimple: 'Grade 3',
    section: 'A',
    parentId: 'par-3',
    parentName: 'Marcus Vance',
    phone: '+91 98221 00187',
    email: 'm.vance@inbox.net',
    motherName: 'Claire Vance',
    address: 'Plot 44, Hill View Enclave, Aundh, Pune',
    admissionDate: '2023-01-15',
    status: 'Active',
    avatar: '',
    attendanceRate: 89.1,
    totalFee: 48000,
    paidFee: 16000,
    pendingFee: 32000,
    feeStatus: 'Overdue',
    overdueDays: 22,
    emergencyPhone: '+91 98221 00187',
  },
  {
    id: 'stu-4',
    studentId: 'GR-1045',
    firstName: 'Maya',
    lastName: 'Patel',
    fullName: 'Maya Patel',
    dob: '2016-01-30',
    gender: 'Female',
    age: 8,
    bloodGroup: 'AB+',
    classId: 'cls-6',
    className: 'Grade 4 - Section B',
    classSimple: 'Grade 4',
    section: 'B',
    parentId: 'par-4',
    parentName: 'Raj Patel',
    phone: '+91 98221 00163',
    email: 'raj.patel@techgrp.com',
    motherName: 'Sunita Patel',
    address: 'Flat 502, Sky High Towers, Kothrud, Pune',
    admissionDate: '2022-09-02',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkO-xa8MfRqvyWfeavoz34NhRlc8slSgpz-caGTDPdoNzUSanJ9B8sfhb2KIpzv8FFbS_-uRYHHF0VewnzwIZ-iDgEHMsche_lpkaHxhBN29BD-008XR2XOF48Xh3EoqiwKhyRD5pZLvjS6F14poJUSsHp7oQX4yuvHllWWVHIUK7rxDZg71roSB8k9k3n39G50VpwF6t0wdryk4IkkZSfxc5UH8O9V4Zq_DbU_mkE6kU8p6emhafV',
    attendanceRate: 99.0,
    totalFee: 50000,
    paidFee: 26000,
    pendingFee: 24000,
    feeStatus: 'Overdue',
    overdueDays: 15,
    emergencyPhone: '+91 98221 00163',
  },
  {
    id: 'stu-5',
    studentId: 'GR-1046',
    firstName: 'Oliver',
    lastName: 'Brown',
    fullName: 'Oliver Brown',
    dob: '2016-05-18',
    gender: 'Male',
    age: 8,
    bloodGroup: 'O-',
    classId: 'cls-5',
    className: 'Grade 3 - Section B',
    classSimple: 'Grade 3',
    section: 'B',
    parentId: 'par-5',
    parentName: 'Jonathan Brown',
    phone: '+91 98221 00112',
    email: 'jbrown@apexcorp.com',
    motherName: 'Sarah Brown',
    address: '88 River Road, Kalyani Nagar, Pune',
    admissionDate: '2022-09-03',
    status: 'Active',
    avatar: '',
    attendanceRate: 94.4,
    totalFee: 48000,
    paidFee: 24000,
    pendingFee: 24000,
    feeStatus: 'Partial',
    overdueDays: 0,
    emergencyPhone: '+91 98221 00112',
  },
  {
    id: 'stu-6',
    studentId: 'GR-1047',
    firstName: 'Emma',
    lastName: 'Wilson',
    fullName: 'Emma Wilson',
    dob: '2016-07-12',
    gender: 'Female',
    age: 8,
    bloodGroup: 'A-',
    classId: 'cls-5',
    className: 'Grade 3 - Section B',
    classSimple: 'Grade 3',
    section: 'B',
    parentId: 'par-6',
    parentName: 'Andrew Wilson',
    phone: '+91 98221 00177',
    email: 'a.wilson@designhub.io',
    motherName: 'Rachel Wilson',
    address: '12 Palm Meadows, Viman Nagar, Pune',
    admissionDate: '2022-10-10',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAlcX_QOMNXku9MMW78asMYRwvoAR2ltxWsaDZfUbiJCAbEPCi8frm_-8GWyQtlsy4SWtkFo2_BklCasSaJo2o6pI5mtCHFfAfEx78ud_EWp2FBq5qXsBfM8pKsVM47q-rIiD43eaZPaju07zloIM62D9vC_Esnhw5rjqurw64LQu7dRtYCUK5S3M_O7gaiCOZWIjPulFJPGSdzV4KEP_DUkSHmx06o06mA7z4Cbcv_soBdmda5c6Yt',
    attendanceRate: 97.8,
    totalFee: 48000,
    paidFee: 48000,
    pendingFee: 0,
    feeStatus: 'Paid in Full',
    overdueDays: 0,
    emergencyPhone: '+91 98221 00177',
  },
  {
    id: 'stu-7',
    studentId: 'GR-1048',
    firstName: 'Zachary',
    lastName: 'Knight',
    fullName: 'Zachary Knight',
    dob: '2015-12-03',
    gender: 'Male',
    age: 9,
    bloodGroup: 'B-',
    classId: 'cls-4',
    className: 'Grade 3 - Section A',
    classSimple: 'Grade 3',
    section: 'A',
    parentId: 'par-7',
    parentName: 'Samuel Knight',
    phone: '+91 98221 00131',
    email: 'samuel.knight@lawfirm.com',
    motherName: 'Diana Knight',
    address: '304 High Street, Camp, Pune',
    admissionDate: '2022-09-01',
    status: 'Active',
    avatar: '',
    attendanceRate: 93.0,
    totalFee: 48000,
    paidFee: 48000,
    pendingFee: 0,
    feeStatus: 'Paid in Full',
    overdueDays: 0,
    emergencyPhone: '+91 98221 00131',
  },
  {
    id: 'stu-8',
    studentId: 'GR-1049',
    firstName: 'Chloe',
    lastName: 'Taylor',
    fullName: 'Chloe Taylor',
    dob: '2016-10-04',
    gender: 'Female',
    age: 8,
    bloodGroup: 'O+',
    classId: 'cls-4',
    className: 'Grade 3 - Section A',
    classSimple: 'Grade 3',
    section: 'A',
    parentId: 'par-8',
    parentName: 'Peter Taylor',
    phone: '+91 98221 00199',
    email: 'p.taylor@medcenter.org',
    motherName: 'Jessica Taylor',
    address: '19 Park View Avenue, Model Colony, Pune',
    admissionDate: '2022-11-11',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuChyKTu0F-UZR69T1QWN37zCk_m8qa93rwTbk1vQGn7Uwc4qs3oWe05ozbUJ1a8nKQoSmGqEVKZ34M0qpW1Io_LidWnO6T1S1e3dqVCW8VKKHc55aGTCMuk6R8jmqZ9KmRIVVypli264WHitq8rKyMbEe2A9GHy_grOKcI6NnvE4kZL3KiNIl8xtBeLoiFVSidcjfXx8XhVya6_rn0rXxnAa_wjg_BdVh-hHAktTsnnFdmv9qhcLqYJ',
    attendanceRate: 91.5,
    totalFee: 48000,
    paidFee: 16000,
    pendingFee: 32000,
    feeStatus: 'Overdue',
    overdueDays: 18,
    emergencyPhone: '+91 98221 00199',
  },
  {
    id: 'stu-9',
    studentId: 'GR-1050',
    firstName: 'Aarav',
    lastName: 'Sharma',
    fullName: 'Aarav Sharma',
    dob: '2020-03-15',
    gender: 'Male',
    age: 4,
    bloodGroup: 'B+',
    classId: 'cls-10',
    className: 'Junior KG - Section A',
    classSimple: 'Junior KG',
    section: 'A',
    parentId: 'par-11',
    parentName: 'Vikram Sharma',
    phone: '+91 98221 00299',
    email: 'vikram.sharma@corp.in',
    motherName: 'Priyanka Sharma',
    address: 'A-201 Green Acres, Wakad, Pune',
    admissionDate: '2024-06-01',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB7KZla9OjHplMiXnphiP_WkYuaqLfygSvuHghjANoujkXVN3NZyE_yEfYyDye5qPTueybpihuJYbdbeJ2qkEqIFpedAnCJOMMjzlWfMvsid8rSXvgttNu7nsnYlci1lz180DP-okLVAWyWRJ7DVHSmrei7s_lsWs-DvVqJniuTKQyiw-Qy2YtrZZFnkTpBA6vlCFQs7HQnqhWwJIlUMGCckM8DHezPJUJJTp12QAU3MxdUR3a63Jol',
    attendanceRate: 95.0,
    totalFee: 30000,
    paidFee: 20000,
    pendingFee: 10000,
    feeStatus: 'Partial',
    overdueDays: 0,
    emergencyPhone: '+91 98221 00299',
  },
  {
    id: 'stu-10',
    studentId: 'GR-1051',
    firstName: 'Anaya',
    lastName: 'Patil',
    fullName: 'Anaya Patil',
    dob: '2019-07-22',
    gender: 'Female',
    age: 5,
    bloodGroup: 'O+',
    classId: 'cls-11',
    className: 'Senior KG - Section A',
    classSimple: 'Senior KG',
    section: 'A',
    parentId: 'par-12',
    parentName: 'Sanjay Patil',
    phone: '+91 98221 00311',
    email: 'sanjay.patil@agri.com',
    motherName: 'Smita Patil',
    address: 'Survey 18, Balewadi, Pune',
    admissionDate: '2023-06-01',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDewxwpiBedO9x7rd73PXmjupnl80SMnqLzbCk3XhwyiRQGBUhSzqtT2EgmOV7kYc07OPcXIjmEJpBfrBDDfHTn5kDxm2gKjYeVFT6xOls7xSb7dcwqgTFO2R3Ja6PCJpC3LGWRe6374hn_k9i0s36FBq9_SnJ4MaxlXu-9XH5WGbuGo2aS2xVEfYwI3ZbxkJd0ktyJsQS64JVwxncSThe7bRfqc21H5Ypkr17XYg6yYKwoO2wOFLlm',
    attendanceRate: 98.0,
    totalFee: 32000,
    paidFee: 32000,
    pendingFee: 0,
    feeStatus: 'Paid in Full',
    overdueDays: 0,
    emergencyPhone: '+91 98221 00311',
  },
  {
    id: 'stu-11',
    studentId: 'GR-1052',
    firstName: 'Marcus',
    lastName: 'Sterling',
    fullName: 'Marcus Sterling',
    dob: '2015-09-14',
    gender: 'Male',
    age: 9,
    bloodGroup: 'A+',
    classId: 'cls-4',
    className: 'Grade 3 - Section A',
    classSimple: 'Grade 3',
    section: 'A',
    parentId: 'par-9',
    parentName: 'Robert Sterling',
    phone: '+91 98221 00215',
    email: 'r.sterling@fintech.co',
    motherName: 'Linda Sterling',
    address: '77 Windsor Estate, Senapati Bapat Rd, Pune',
    admissionDate: '2022-09-01',
    status: 'Active',
    avatar: '',
    attendanceRate: 86.2,
    totalFee: 48000,
    paidFee: 0,
    pendingFee: 48000,
    feeStatus: 'Overdue',
    overdueDays: 42,
    emergencyPhone: '+91 98221 00215',
  },
  {
    id: 'stu-12',
    studentId: 'GR-1053',
    firstName: 'Sophia',
    lastName: 'Ramirez',
    fullName: 'Sophia Ramirez',
    dob: '2014-06-18',
    gender: 'Female',
    age: 10,
    bloodGroup: 'B+',
    classId: 'cls-8',
    className: 'Grade 5 - Section B',
    classSimple: 'Grade 5',
    section: 'B',
    parentId: 'par-10',
    parentName: 'Elena Ramirez',
    phone: '+91 98221 00244',
    email: 'elena.ramirez@artstudio.com',
    motherName: 'Elena Ramirez',
    address: '45 Magnolia Court, Bavdhan, Pune',
    admissionDate: '2021-08-15',
    status: 'Active',
    avatar: '',
    attendanceRate: 92.4,
    totalFee: 55000,
    paidFee: 25000,
    pendingFee: 30000,
    feeStatus: 'Overdue',
    overdueDays: 34,
    emergencyPhone: '+91 98221 00244',
  }
];

export const initialPayments = [
  {
    id: 'pay-1',
    receiptNumber: 'REC-2024-8842',
    studentId: 'stu-4',
    studentName: 'Julian Morales',
    className: 'Grade 4-B',
    amountPaid: 26000,
    paymentDate: '2024-10-15',
    paymentTime: '09:42 AM',
    paymentMode: 'Bank Transfer',
    transactionRef: 'HDFC-IMPS-8921',
    remarks: 'Term 2 installment clearance',
    status: 'Completed',
  },
  {
    id: 'pay-2',
    receiptNumber: 'REC-2024-8841',
    studentId: 'stu-2',
    studentName: 'Emma Phillips',
    className: 'Grade 1-A',
    amountPaid: 42000,
    paymentDate: '2024-10-15',
    paymentTime: '09:15 AM',
    paymentMode: 'Cheque',
    transactionRef: 'CHQ-552910',
    remarks: 'Annual fee full payment',
    status: 'Completed',
  },
  {
    id: 'pay-3',
    receiptNumber: 'REC-2024-8840',
    studentId: 'stu-10',
    studentName: 'Tyler Chen',
    className: 'Kindergarten',
    amountPaid: 17500,
    paymentDate: '2024-10-15',
    paymentTime: '08:50 AM',
    paymentMode: 'Cash',
    transactionRef: 'CASH-REC-01',
    remarks: 'Term 1 fee counter cash',
    status: 'Completed',
  },
  {
    id: 'pay-4',
    receiptNumber: 'REC-2024-8835',
    studentId: 'stu-1',
    studentName: 'Liam Chen',
    className: 'Grade 3-A',
    amountPaid: 24000,
    paymentDate: '2024-10-12',
    paymentTime: '11:20 AM',
    paymentMode: 'UPI',
    transactionRef: 'UPI-9821092841',
    remarks: 'First installment paid via GPay',
    status: 'Completed',
  },
  {
    id: 'pay-5',
    receiptNumber: 'REC-2024-8829',
    studentId: 'stu-9',
    studentName: 'Aarav Sharma',
    className: 'Junior KG A',
    amountPaid: 20000,
    paymentDate: '2024-10-10',
    paymentTime: '02:30 PM',
    paymentMode: 'UPI',
    transactionRef: 'UPI-8812390192',
    remarks: 'Admission fee part clearance',
    status: 'Completed',
  },
  {
    id: 'pay-6',
    receiptNumber: 'REC-2024-8811',
    studentId: 'stu-6',
    studentName: 'Emma Wilson',
    className: 'Grade 3-B',
    amountPaid: 48000,
    paymentDate: '2024-10-05',
    paymentTime: '10:15 AM',
    paymentMode: 'Bank Transfer',
    transactionRef: 'NEFT-8812004',
    remarks: 'Full year tuition & lab package',
    status: 'Completed',
  }
];

export const initialAttendanceRosters = {
  'cls-4': [
    { studentId: 'stu-1', rollNo: '01', grId: 'GR-1042', name: 'Liam Chen', status: 'P', prevDay: 'P', remarks: '', house: 'Red Cedar', bus: 'Bus #12' },
    { studentId: 'stu-8', rollNo: '02', grId: 'GR-1049', name: 'Chloe Taylor', status: 'A', prevDay: 'P', remarks: 'Severe Flu / Doctor visit scheduled', house: 'Blue River', bus: 'Walker' },
    { studentId: 'stu-3', rollNo: '03', grId: 'GR-1044', name: 'Lucas Vance', status: 'P', prevDay: 'P', remarks: '', house: 'Green Pines', bus: 'Bus #02' },
    { studentId: 'stu-7', rollNo: '04', grId: 'GR-1048', name: 'Zachary Knight', status: 'P', prevDay: 'P', remarks: '', house: 'Gold Sun', bus: 'Bus #04' },
    { studentId: 'stu-11', rollNo: '05', grId: 'GR-1052', name: 'Marcus Sterling', status: 'A', prevDay: 'A', remarks: 'Unexplained absence • Attempting phone call', house: 'Red Cedar', bus: 'Bus #12' },
    { studentId: 'stu-6', rollNo: '06', grId: 'GR-1047', name: 'Emma Wilson', status: 'L', prevDay: 'P', remarks: 'Late due to heavy traffic', house: 'Blue River', bus: 'Walker' },
  ]
};
